// WS3: PDF Document — React components for @react-pdf/renderer
import React from 'react';
import { Document, Page, View, Text } from '@react-pdf/renderer';
import type { StreetSegment, ValidationResult, CrossSectionElement } from '@/lib/types';
import { styles, colors, ELEMENT_TYPE_COLORS } from './pdf-styles';

// ── Helper functions ────────────────────────────────────────────────────────

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return iso;
  }
}

function elementDisplayName(type: string): string {
  return type
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function sideLabel(side: string): string {
  return side.charAt(0).toUpperCase() + side.slice(1);
}

function severitySymbol(severity: string): string {
  switch (severity) {
    case 'error': return 'FAIL';
    case 'warning': return 'WARN';
    case 'info': return 'INFO';
    default: return '--';
  }
}

function getElementStatus(
  element: CrossSectionElement,
  validationResults: ValidationResult[],
): { label: string; color: string } {
  const elementResults = validationResults.filter((r) => r.elementId === element.id);
  if (elementResults.some((r) => r.severity === 'error')) {
    return { label: 'FAIL', color: colors.error };
  }
  if (elementResults.some((r) => r.severity === 'warning')) {
    return { label: 'WARN', color: colors.warning };
  }
  return { label: 'PASS', color: colors.pass };
}

// ── Reusable page components ────────────────────────────────────────────────

function PageHeader({ streetName }: { streetName: string }) {
  return (
    <View style={styles.header}>
      <Text style={styles.headerTitle}>{streetName} — Street Design Concept Report</Text>
      <Text style={styles.headerDate}>Curbwise</Text>
    </View>
  );
}

function PageFooter({ pageLabel }: { pageLabel: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>Generated by Curbwise</Text>
      <Text style={styles.footerText}>{pageLabel}</Text>
    </View>
  );
}

// ── Page 1: Cover/Summary ───────────────────────────────────────────────────

function CoverPage({ street }: { street: StreetSegment }) {
  return (
    <Page size="LETTER" style={styles.page}>
      <View style={styles.coverContainer}>
        <Text style={styles.coverTitle}>Street Design{'\n'}Concept Report</Text>
        <View style={styles.coverDivider} />
        <Text style={styles.coverStreetName}>{street.name}</Text>
        <Text style={styles.coverMeta}>
          Total ROW Width: {street.totalROWWidth} ft
        </Text>
        <Text style={styles.coverMeta}>
          Curb-to-Curb Width: {street.curbToCurbWidth} ft
        </Text>
        <Text style={styles.coverMeta}>
          Direction: {street.direction === 'two-way' ? 'Two-Way' : 'One-Way'}
        </Text>
        <Text style={styles.coverMeta}>
          Functional Class: {street.functionalClass
            .split('-')
            .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
            .join(' ')}
        </Text>
        {street.metadata.templateId && (
          <Text style={styles.coverMeta}>
            Template: {street.metadata.templateId}
          </Text>
        )}
        <View style={[styles.coverDivider, { marginTop: 30 }]} />
        <Text style={styles.coverMeta}>
          {formatDate(street.metadata.createdAt)}
        </Text>
      </View>
      <PageFooter pageLabel="Cover" />
    </Page>
  );
}

// ── Page 2: Cross-Section Diagram ───────────────────────────────────────────

function CrossSectionPage({ street }: { street: StreetSegment }) {
  const totalWidth = street.elements.reduce((acc, el) => acc + el.width, 0);

  return (
    <Page size="LETTER" style={styles.page}>
      <PageHeader streetName={street.name} />
      <Text style={styles.sectionTitle}>Cross-Section Diagram</Text>
      <Text style={{ fontSize: 9, color: colors.textLight, marginBottom: 8 }}>
        Total Right-of-Way: {street.totalROWWidth} ft | Elements shown proportional
        to width
      </Text>

      {/* Simplified cross-section using View primitives */}
      <View style={styles.crossSectionContainer}>
        {street.elements.map((el) => {
          const widthPercent = `${((el.width / totalWidth) * 100).toFixed(1)}%`;
          const bgColor = ELEMENT_TYPE_COLORS[el.type] || colors.buffer;
          // Use white text on dark backgrounds, dark text on light ones
          const isDark = ['travel-lane', 'turn-lane', 'bike-lane-protected', 'transit-lane'].includes(el.type);
          const textColor = isDark ? colors.white : '#333333';

          return (
            <View
              key={el.id}
              style={[
                styles.crossSectionElement,
                {
                  width: widthPercent,
                  backgroundColor: bgColor,
                  borderRightWidth: 0.5,
                  borderRightColor: 'rgba(255,255,255,0.4)',
                },
              ]}
            >
              <Text style={[styles.crossSectionLabel, { color: textColor }]}>
                {el.label || elementDisplayName(el.type)}
              </Text>
              <Text style={[styles.crossSectionWidth, { color: textColor }]}>
                {el.width} ft
              </Text>
            </View>
          );
        })}
      </View>

      {/* Legend */}
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 12, gap: 8 }}>
        {street.elements.map((el) => (
          <View key={el.id} style={{ flexDirection: 'row', alignItems: 'center', marginRight: 12, marginBottom: 4 }}>
            <View
              style={{
                width: 10,
                height: 10,
                backgroundColor: ELEMENT_TYPE_COLORS[el.type] || colors.buffer,
                marginRight: 4,
                borderRadius: 1,
              }}
            />
            <Text style={{ fontSize: 7, color: colors.text }}>
              {el.label || elementDisplayName(el.type)} ({el.width} ft)
            </Text>
          </View>
        ))}
      </View>

      <PageFooter pageLabel="Cross-Section" />
    </Page>
  );
}

// ── Page 3: Width Table ─────────────────────────────────────────────────────

function WidthTablePage({
  street,
  validationResults,
}: {
  street: StreetSegment;
  validationResults: ValidationResult[];
}) {
  // Column widths as percentages
  const col = { type: '18%', side: '10%', width: '10%', recMin: '12%', rec: '12%', prowag: '12%', status: '10%', source: '16%' };

  return (
    <Page size="LETTER" style={styles.page}>
      <PageHeader streetName={street.name} />
      <Text style={styles.sectionTitle}>Element Width Summary</Text>

      <View style={styles.table}>
        {/* Header row */}
        <View style={styles.tableHeader}>
          <Text style={[styles.tableHeaderCell, { width: col.type }]}>Element</Text>
          <Text style={[styles.tableHeaderCell, { width: col.side }]}>Side</Text>
          <Text style={[styles.tableHeaderCell, { width: col.width }]}>Width</Text>
          <Text style={[styles.tableHeaderCell, { width: col.recMin }]}>Rec. Min</Text>
          <Text style={[styles.tableHeaderCell, { width: col.rec }]}>Recommended</Text>
          <Text style={[styles.tableHeaderCell, { width: col.prowag }]}>PROWAG Min</Text>
          <Text style={[styles.tableHeaderCell, { width: col.status }]}>Status</Text>
          <Text style={[styles.tableHeaderCell, { width: col.source }]}>Source</Text>
        </View>

        {/* Data rows */}
        {street.elements.map((el, i) => {
          const status = getElementStatus(el, validationResults);
          const rowStyle = i % 2 === 0 ? styles.tableRow : styles.tableRowAlt;

          return (
            <View key={el.id} style={rowStyle}>
              <Text style={[styles.tableCell, { width: col.type }]}>
                {el.label || elementDisplayName(el.type)}
              </Text>
              <Text style={[styles.tableCell, { width: col.side }]}>
                {sideLabel(el.side)}
              </Text>
              <Text style={[styles.tableCell, { width: col.width, fontFamily: 'Helvetica-Bold' }]}>
                {el.width} ft
              </Text>
              <Text style={[styles.tableCell, { width: col.recMin }]}>
                {el.constraints.recommendedMin} ft
              </Text>
              <Text style={[styles.tableCell, { width: col.rec }]}>
                {el.constraints.recommended} ft
              </Text>
              <Text style={[styles.tableCell, { width: col.prowag }]}>
                {el.constraints.prowagRequired ? `${el.constraints.absoluteMin} ft` : '--'}
              </Text>
              <Text
                style={[
                  styles.tableCell,
                  { width: col.status, fontFamily: 'Helvetica-Bold', color: status.color },
                ]}
              >
                {status.label}
              </Text>
              <Text style={[styles.tableCell, { width: col.source, fontSize: 6 }]}>
                {el.constraints.source}
              </Text>
            </View>
          );
        })}
      </View>

      {/* Summary boxes */}
      <View style={styles.summaryBox}>
        <View style={styles.summaryItem}>
          <Text style={styles.summaryValue}>{street.totalROWWidth}</Text>
          <Text style={styles.summaryLabel}>Total ROW (ft)</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={styles.summaryValue}>{street.curbToCurbWidth}</Text>
          <Text style={styles.summaryLabel}>Curb-to-Curb (ft)</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={styles.summaryValue}>{street.elements.length}</Text>
          <Text style={styles.summaryLabel}>Elements</Text>
        </View>
      </View>

      <PageFooter pageLabel="Width Table" />
    </Page>
  );
}

// ── Page 4: Standards Compliance ─────────────────────────────────────────────

function CompliancePage({
  street,
  validationResults,
}: {
  street: StreetSegment;
  validationResults: ValidationResult[];
}) {
  const errors = validationResults.filter((r) => r.severity === 'error');
  const warnings = validationResults.filter((r) => r.severity === 'warning');
  const infos = validationResults.filter((r) => r.severity === 'info');

  const prowagResults = validationResults.filter((r) => r.constraint === 'prowag');
  const nactoResults = validationResults.filter((r) => r.constraint === 'nacto');

  const prowagPass = prowagResults.length === 0;
  const nactoViolations = nactoResults.filter((r) => r.severity === 'warning').length;

  return (
    <Page size="LETTER" style={styles.page}>
      <PageHeader streetName={street.name} />
      <Text style={styles.sectionTitle}>Standards Compliance</Text>

      {/* Compliance summary */}
      <View style={styles.summaryBox}>
        <View style={styles.summaryItem}>
          <Text style={[styles.summaryValue, { color: prowagPass ? colors.pass : colors.error }]}>
            {prowagPass ? 'PASS' : 'FAIL'}
          </Text>
          <Text style={styles.summaryLabel}>PROWAG Compliance</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={[styles.summaryValue, { color: nactoViolations === 0 ? colors.pass : colors.warning }]}>
            {nactoViolations === 0 ? 'PASS' : `${nactoViolations} issues`}
          </Text>
          <Text style={styles.summaryLabel}>NACTO Compliance</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={[styles.summaryValue, { color: errors.length > 0 ? colors.error : colors.pass }]}>
            {errors.length}
          </Text>
          <Text style={styles.summaryLabel}>Errors</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={[styles.summaryValue, { color: warnings.length > 0 ? colors.warning : colors.pass }]}>
            {warnings.length}
          </Text>
          <Text style={styles.summaryLabel}>Warnings</Text>
        </View>
      </View>

      {/* Errors */}
      {errors.length > 0 && (
        <>
          <Text style={styles.sectionSubtitle}>Errors ({errors.length})</Text>
          {errors.map((r, i) => (
            <View key={`err-${i}`} style={[styles.validationItem, { borderLeftColor: colors.error }]}>
              <View style={{ flex: 1 }}>
                <Text style={styles.validationMessage}>
                  <Text style={{ fontFamily: 'Helvetica-Bold', color: colors.error }}>
                    {severitySymbol(r.severity)}{' '}
                  </Text>
                  {r.message}
                </Text>
                <Text style={styles.validationCitation}>
                  {r.citation} | Current: {r.currentValue} ft | Required: {r.requiredValue} ft
                </Text>
              </View>
            </View>
          ))}
        </>
      )}

      {/* Warnings */}
      {warnings.length > 0 && (
        <>
          <Text style={styles.sectionSubtitle}>Warnings ({warnings.length})</Text>
          {warnings.map((r, i) => (
            <View key={`warn-${i}`} style={[styles.validationItem, { borderLeftColor: colors.warning }]}>
              <View style={{ flex: 1 }}>
                <Text style={styles.validationMessage}>
                  <Text style={{ fontFamily: 'Helvetica-Bold', color: colors.warning }}>
                    {severitySymbol(r.severity)}{' '}
                  </Text>
                  {r.message}
                </Text>
                <Text style={styles.validationCitation}>
                  {r.citation} | Current: {r.currentValue} ft | Required: {r.requiredValue} ft
                </Text>
              </View>
            </View>
          ))}
        </>
      )}

      {/* Info */}
      {infos.length > 0 && (
        <>
          <Text style={styles.sectionSubtitle}>Informational ({infos.length})</Text>
          {infos.map((r, i) => (
            <View key={`info-${i}`} style={[styles.validationItem, { borderLeftColor: colors.info }]}>
              <View style={{ flex: 1 }}>
                <Text style={styles.validationMessage}>
                  <Text style={{ fontFamily: 'Helvetica-Bold', color: colors.info }}>
                    {severitySymbol(r.severity)}{' '}
                  </Text>
                  {r.message}
                </Text>
                <Text style={styles.validationCitation}>
                  {r.citation} | Current: {r.currentValue} ft | Recommended: {r.requiredValue} ft
                </Text>
              </View>
            </View>
          ))}
        </>
      )}

      {/* No issues */}
      {validationResults.length === 0 && (
        <View style={[styles.validationItem, { borderLeftColor: colors.pass }]}>
          <Text style={[styles.validationMessage, { color: colors.pass, fontFamily: 'Helvetica-Bold' }]}>
            All elements meet PROWAG and NACTO standards. No issues found.
          </Text>
        </View>
      )}

      <PageFooter pageLabel="Standards Compliance" />
    </Page>
  );
}

// ── Page 5: Before/After Comparison ─────────────────────────────────────────

function ComparisonPage({
  currentStreet,
  beforeStreet,
}: {
  currentStreet: StreetSegment;
  beforeStreet: StreetSegment;
}) {
  // Build element comparison: match by index position for simple comparison
  const maxElements = Math.max(currentStreet.elements.length, beforeStreet.elements.length);
  const col = { label: '22%', before: '18%', after: '18%', change: '18%', type: '24%' };

  return (
    <Page size="LETTER" style={styles.page}>
      <PageHeader streetName={currentStreet.name} />
      <Text style={styles.sectionTitle}>Before / After Comparison</Text>

      {/* Summary comparison */}
      <View style={styles.summaryBox}>
        <View style={styles.summaryItem}>
          <Text style={styles.summaryValue}>{beforeStreet.totalROWWidth}</Text>
          <Text style={styles.summaryLabel}>Before ROW (ft)</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={styles.summaryValue}>{currentStreet.totalROWWidth}</Text>
          <Text style={styles.summaryLabel}>After ROW (ft)</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={styles.summaryValue}>{beforeStreet.elements.length}</Text>
          <Text style={styles.summaryLabel}>Before Elements</Text>
        </View>
        <View style={styles.summaryItem}>
          <Text style={styles.summaryValue}>{currentStreet.elements.length}</Text>
          <Text style={styles.summaryLabel}>After Elements</Text>
        </View>
      </View>

      <Text style={styles.sectionSubtitle}>Element-by-Element Comparison</Text>

      <View style={styles.table}>
        <View style={styles.tableHeader}>
          <Text style={[styles.tableHeaderCell, { width: col.label }]}>Position</Text>
          <Text style={[styles.tableHeaderCell, { width: col.type }]}>Element</Text>
          <Text style={[styles.tableHeaderCell, { width: col.before }]}>Before (ft)</Text>
          <Text style={[styles.tableHeaderCell, { width: col.after }]}>After (ft)</Text>
          <Text style={[styles.tableHeaderCell, { width: col.change }]}>Change</Text>
        </View>

        {Array.from({ length: maxElements }).map((_, i) => {
          const before = beforeStreet.elements[i];
          const after = currentStreet.elements[i];
          const rowStyle = i % 2 === 0 ? styles.tableRow : styles.tableRowAlt;

          const beforeWidth = before?.width ?? 0;
          const afterWidth = after?.width ?? 0;
          const diff = afterWidth - beforeWidth;
          const diffStr = diff > 0 ? `+${diff.toFixed(1)}` : diff.toFixed(1);
          const diffColor = diff > 0 ? colors.pass : diff < 0 ? colors.error : colors.text;

          return (
            <View key={`cmp-${i}`} style={rowStyle}>
              <Text style={[styles.tableCell, { width: col.label }]}>
                #{i + 1}
              </Text>
              <Text style={[styles.tableCell, { width: col.type }]}>
                {after
                  ? after.label || elementDisplayName(after.type)
                  : before
                    ? `(removed) ${before.label || elementDisplayName(before.type)}`
                    : '--'}
              </Text>
              <Text style={[styles.tableCell, { width: col.before }]}>
                {before ? `${before.width}` : '--'}
              </Text>
              <Text style={[styles.tableCell, { width: col.after }]}>
                {after ? `${after.width}` : '--'}
              </Text>
              <Text
                style={[
                  styles.tableCell,
                  { width: col.change, fontFamily: 'Helvetica-Bold', color: diffColor },
                ]}
              >
                {before || after ? diffStr : '--'}
              </Text>
            </View>
          );
        })}
      </View>

      <PageFooter pageLabel="Before / After" />
    </Page>
  );
}

// ── Final Page: Disclaimer ──────────────────────────────────────────────────

function DisclaimerPage({ street }: { street: StreetSegment }) {
  return (
    <Page size="LETTER" style={styles.page}>
      <PageHeader streetName={street.name} />

      <View style={styles.disclaimerBox}>
        <Text style={styles.disclaimerTitle}>Disclaimer</Text>

        <Text style={styles.disclaimerText}>
          This report is for conceptual planning purposes only. It is intended to support
          early-stage design discussions and community engagement, not to serve as construction
          documentation.
        </Text>

        <Text style={styles.disclaimerText}>
          Design dimensions should be verified by a licensed professional engineer before
          advancing to preliminary or final design. Site-specific conditions including
          utilities, drainage, grading, right-of-way boundaries, and subsurface conditions
          must be evaluated by qualified professionals.
        </Text>

        <Text style={styles.disclaimerText}>
          PROWAG citations reference the Public Right-of-Way Accessibility Guidelines
          (proposed rule, 2023 edition). NACTO citations reference the NACTO Urban Street
          Design Guide (2013) and the NACTO Transit Street Design Guide (2016). Local
          jurisdiction standards may supersede these national guidelines.
        </Text>

        <Text style={styles.disclaimerText}>
          The cross-section visualization is a schematic representation. Actual street
          geometry will vary based on horizontal and vertical alignment, intersection design,
          and other factors not represented in this cross-section view.
        </Text>

        <Text style={[styles.disclaimerText, { marginTop: 12, fontFamily: 'Helvetica-Bold' }]}>
          Generated: {formatDate(new Date().toISOString())}
        </Text>
        <Text style={styles.disclaimerText}>
          Tool: Curbwise v0.1.0
        </Text>
      </View>

      <PageFooter pageLabel="Disclaimer" />
    </Page>
  );
}

// ── Main Document Component ─────────────────────────────────────────────────

interface StreetReportDocumentProps {
  currentStreet: StreetSegment;
  beforeStreet: StreetSegment | null;
  validationResults: ValidationResult[];
}

export function StreetReportDocument({
  currentStreet,
  beforeStreet,
  validationResults,
}: StreetReportDocumentProps) {
  return (
    <Document
      title={`${currentStreet.name} — Street Design Concept Report`}
      author="Curbwise"
      subject="Street Design Concept Report"
    >
      {/* Page 1: Cover */}
      <CoverPage street={currentStreet} />

      {/* Page 2: Cross-Section */}
      <CrossSectionPage street={currentStreet} />

      {/* Page 3: Width Table */}
      <WidthTablePage street={currentStreet} validationResults={validationResults} />

      {/* Page 4: Standards Compliance */}
      <CompliancePage street={currentStreet} validationResults={validationResults} />

      {/* Page 5: Before/After (conditional) */}
      {beforeStreet && (
        <ComparisonPage currentStreet={currentStreet} beforeStreet={beforeStreet} />
      )}

      {/* Final Page: Disclaimer */}
      <DisclaimerPage street={currentStreet} />
    </Document>
  );
}
