import type { BeforePreset } from '@/lib/types';
import { DEFAULT_CONSTRAINTS } from '@/lib/constants';

// "What does this street look like today?" presets
// Each maps to a StreetSegment via the proposal store.

export const BEFORE_PRESETS: BeforePreset[] = [
  {
    id: '2-lane-residential',
    label: '2 lanes, residential',
    description: 'Quiet neighborhood street — one lane each way',
    rowWidth: 40,
    direction: 'two-way',
    functionalClass: 'local',
    elements: [
      { type: 'sidewalk', side: 'left', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
      { type: 'curb', side: 'left', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'travel-lane', side: 'left', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'curb', side: 'right', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'sidewalk', side: 'right', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
    ],
    // NOTE: Widths sum to 33 — the adapter fits to 40 ft ROW
    suggestedTransformations: ['shared-street-residential', 'complete-street-local'],
  },
  {
    id: '2-lane-with-parking',
    label: '2 lanes with parking',
    description: 'Common on neighborhood main streets and mixed-use corridors',
    rowWidth: 50,
    direction: 'two-way',
    functionalClass: 'local',
    elements: [
      { type: 'sidewalk', side: 'left', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
      { type: 'curb', side: 'left', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'parking-lane', side: 'left', width: 8, constraints: DEFAULT_CONSTRAINTS['parking-lane'], locked: false, label: 'Parking' },
      { type: 'travel-lane', side: 'left', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'parking-lane', side: 'right', width: 8, constraints: DEFAULT_CONSTRAINTS['parking-lane'], locked: false, label: 'Parking' },
      { type: 'curb', side: 'right', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'sidewalk', side: 'right', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
    ],
    suggestedTransformations: ['protected-bike-lane-two-way', 'complete-street-local', 'shared-street-commercial'],
  },
  {
    id: '4-lane-no-median',
    label: '4 lanes, no median',
    description: 'Typical undivided collector or minor arterial',
    rowWidth: 60,
    direction: 'two-way',
    functionalClass: 'collector',
    elements: [
      { type: 'sidewalk', side: 'left', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
      { type: 'curb', side: 'left', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'travel-lane', side: 'left', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'left', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'curb', side: 'right', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'sidewalk', side: 'right', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
    ],
    suggestedTransformations: ['road-diet-4to3', 'protected-bike-lane-one-way', 'complete-street-collector'],
  },
  {
    id: '4-lane-with-parking',
    label: '4 lanes with parking',
    description: 'Common on collectors and minor arterials in urban areas',
    rowWidth: 66,
    direction: 'two-way',
    functionalClass: 'collector',
    elements: [
      { type: 'sidewalk', side: 'left', width: 5.5, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
      { type: 'curb', side: 'left', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'parking-lane', side: 'left', width: 8, constraints: DEFAULT_CONSTRAINTS['parking-lane'], locked: false, label: 'Parking' },
      { type: 'travel-lane', side: 'left', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'left', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 10, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'parking-lane', side: 'right', width: 8, constraints: DEFAULT_CONSTRAINTS['parking-lane'], locked: false, label: 'Parking' },
      { type: 'curb', side: 'right', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'sidewalk', side: 'right', width: 5.5, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
    ],
    suggestedTransformations: ['road-diet-with-parking', 'protected-bike-lane-one-way', 'complete-street-collector'],
  },
  {
    id: '4-lane-with-median',
    label: '4 lanes with median',
    description: 'Divided arterial with a raised or painted median',
    rowWidth: 70,
    direction: 'two-way',
    functionalClass: 'minor-arterial',
    elements: [
      { type: 'sidewalk', side: 'left', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
      { type: 'curb', side: 'left', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'travel-lane', side: 'left', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'left', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'median', side: 'center', width: 8, constraints: DEFAULT_CONSTRAINTS['median'], locked: false, label: 'Median' },
      { type: 'travel-lane', side: 'right', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 11, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'curb', side: 'right', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'sidewalk', side: 'right', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
    ],
    suggestedTransformations: ['protected-bike-lane-one-way', 'complete-street-collector', 'transit-priority-dedicated'],
  },
  {
    id: '5-lane-center-turn',
    label: '5 lanes (center turn)',
    description: 'Wide road with a center turn lane — classic suburban arterial',
    rowWidth: 80,
    direction: 'two-way',
    functionalClass: 'minor-arterial',
    elements: [
      { type: 'sidewalk', side: 'left', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
      { type: 'curb', side: 'left', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'travel-lane', side: 'left', width: 12, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'left', width: 12, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'turn-lane', side: 'center', width: 12, constraints: DEFAULT_CONSTRAINTS['turn-lane'], locked: false, label: 'Center Turn Lane' },
      { type: 'travel-lane', side: 'right', width: 12, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'travel-lane', side: 'right', width: 12, constraints: DEFAULT_CONSTRAINTS['travel-lane'], locked: false, label: 'Travel Lane' },
      { type: 'curb', side: 'right', width: 0.5, constraints: DEFAULT_CONSTRAINTS['curb'], locked: true, label: 'Curb' },
      { type: 'sidewalk', side: 'right', width: 6, constraints: DEFAULT_CONSTRAINTS['sidewalk'], locked: false, label: 'Sidewalk' },
    ],
    suggestedTransformations: ['road-diet-with-parking', 'protected-bike-lane-parking', 'transit-priority-brt'],
  },
];
