import type { IntersectionImprovement } from '@/lib/types/intersection';

export const INTERSECTION_IMPROVEMENTS: IntersectionImprovement[] = [
  // ── Traffic Control ──
  {
    id: 'add-stop-sign',
    category: 'traffic-control',
    label: 'Add stop sign',
    description: 'Install stop sign on uncontrolled approach',
    icon: '🛑',
    relevantCrashModes: ['motorist', 'pedestrian', 'cyclist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 1,
    complexity: 'quick-win',
    excludes: ['upgrade-to-signal', 'convert-to-roundabout'],
  },
  {
    id: 'upgrade-to-signal',
    category: 'traffic-control',
    label: 'Upgrade to traffic signal',
    description: 'Install full traffic signal with pedestrian phases',
    icon: '🚦',
    relevantCrashModes: ['motorist', 'pedestrian', 'cyclist'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 3,
    complexity: 'major',
    excludes: ['add-stop-sign', 'convert-to-roundabout'],
  },
  {
    id: 'signal-timing-review',
    category: 'traffic-control',
    label: 'Signal timing review',
    description: 'Optimize signal timing for all modes',
    icon: '⏱',
    relevantCrashModes: ['motorist', 'pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 2,
    complexity: 'quick-win',
    requires: ['signalized'],
  },
  {
    id: 'convert-to-roundabout',
    category: 'traffic-control',
    label: 'Convert to roundabout',
    description: 'Replace signal/stop with modern roundabout',
    icon: '🔄',
    relevantCrashModes: ['motorist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 5,
    complexity: 'major',
    excludes: ['add-stop-sign', 'upgrade-to-signal'],
  },

  // ── Pedestrian ──
  {
    id: 'add-crosswalks',
    category: 'pedestrian',
    label: 'Add crosswalks',
    description: 'Mark crosswalks on all approaches',
    icon: '🚶',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 1,
    complexity: 'quick-win',
  },
  {
    id: 'high-visibility-markings',
    category: 'pedestrian',
    label: 'High-visibility crosswalk markings',
    description: 'Continental or ladder-style crosswalk markings',
    icon: '🦓',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 1,
    complexity: 'quick-win',
  },
  {
    id: 'leading-pedestrian-interval',
    category: 'pedestrian',
    label: 'Leading pedestrian interval (LPI)',
    description: 'Give pedestrians a 3-7 second head start at signal',
    icon: '🟢',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 2,
    complexity: 'quick-win',
    requires: ['signalized'],
  },
  {
    id: 'pedestrian-refuge-island',
    category: 'pedestrian',
    label: 'Pedestrian refuge island',
    description: 'Raised median island for two-stage crossing',
    icon: '🏝',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 2,
    complexity: 'moderate',
  },
  {
    id: 'raised-crosswalk',
    category: 'pedestrian',
    label: 'Raised crosswalk',
    description: 'Speed table at crosswalk location',
    icon: '⬆',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 2,
    complexity: 'moderate',
  },

  // ── Accessibility ──
  {
    id: 'curb-ramps',
    category: 'accessibility',
    label: 'ADA curb ramps',
    description: 'Install compliant curb ramps at all corners',
    icon: '♿',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury', 'minor'],
    minimumCrashThreshold: 0,
    complexity: 'quick-win',
  },
  {
    id: 'tactile-warning',
    category: 'accessibility',
    label: 'Tactile warning surfaces',
    description: 'Detectable warning surfaces at curb ramps',
    icon: '🔶',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 0,
    complexity: 'quick-win',
  },
  {
    id: 'accessible-pedestrian-signal',
    category: 'accessibility',
    label: 'Accessible pedestrian signal',
    description: 'APS with locator tone and tactile arrow',
    icon: '🔊',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 0,
    complexity: 'moderate',
    requires: ['signalized'],
  },
  {
    id: 'audible-countdown',
    category: 'accessibility',
    label: 'Audible countdown',
    description: 'Audible countdown timer for pedestrian phase',
    icon: '🔔',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 0,
    complexity: 'quick-win',
    requires: ['signalized'],
  },

  // ── Transit ──
  {
    id: 'bus-bulb',
    category: 'transit',
    label: 'Bus bulb / boarding island',
    description: 'Extend sidewalk to bus stop for level boarding',
    icon: '🚌',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 1,
    complexity: 'moderate',
  },
  {
    id: 'far-side-stop',
    category: 'transit',
    label: 'Far-side stop relocation',
    description: 'Move bus stop to far side of intersection',
    icon: '➡',
    relevantCrashModes: ['pedestrian', 'motorist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 2,
    complexity: 'quick-win',
  },
  {
    id: 'transit-shelter',
    category: 'transit',
    label: 'Transit shelter',
    description: 'Weather-protected waiting area',
    icon: '🏠',
    relevantCrashModes: [],
    relevantSeverities: [],
    minimumCrashThreshold: 0,
    complexity: 'moderate',
  },
  {
    id: 'transit-signal-priority',
    category: 'transit',
    label: 'Transit signal priority',
    description: 'Extend green or advance signal for transit vehicles',
    icon: '🚍',
    relevantCrashModes: ['motorist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 2,
    complexity: 'moderate',
    requires: ['signalized'],
  },

  // ── Safety ──
  {
    id: 'daylighting',
    category: 'safety',
    label: 'Daylighting',
    description: 'Remove parking near corners to improve sight lines',
    icon: '👁',
    relevantCrashModes: ['pedestrian', 'cyclist', 'motorist'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 1,
    complexity: 'quick-win',
  },
  {
    id: 'curb-extensions',
    category: 'safety',
    label: 'Curb extensions / bulbouts',
    description: 'Extend curb to narrow crossing distance',
    icon: '↔',
    relevantCrashModes: ['pedestrian'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 2,
    complexity: 'moderate',
  },
  {
    id: 'tightened-turning-radii',
    category: 'safety',
    label: 'Tightened turning radii',
    description: 'Reduce corner radius to slow turning vehicles',
    icon: '↩',
    relevantCrashModes: ['pedestrian', 'cyclist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 2,
    complexity: 'moderate',
  },
  {
    id: 'speed-table',
    category: 'safety',
    label: 'Speed table',
    description: 'Raised platform across intersection approach',
    icon: '⬆',
    relevantCrashModes: ['pedestrian', 'cyclist', 'motorist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 3,
    complexity: 'moderate',
  },
  {
    id: 'no-turn-on-red',
    category: 'safety',
    label: 'No turn on red',
    description: 'Prohibit right turn on red for pedestrian safety',
    icon: '🚫',
    relevantCrashModes: ['pedestrian', 'cyclist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 1,
    complexity: 'quick-win',
    requires: ['signalized'],
  },

  // ── Cycling ──
  {
    id: 'bike-box',
    category: 'cycling',
    label: 'Bike box',
    description: 'Colored waiting area for cyclists ahead of stop line',
    icon: '🚲',
    relevantCrashModes: ['cyclist'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 1,
    complexity: 'quick-win',
    requires: ['signalized'],
  },
  {
    id: 'protected-intersection',
    category: 'cycling',
    label: 'Protected intersection design',
    description: 'Corner islands and setback crossings for cyclists',
    icon: '🛡',
    relevantCrashModes: ['cyclist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 3,
    complexity: 'major',
  },
  {
    id: 'two-stage-turn',
    category: 'cycling',
    label: 'Two-stage turn queue box',
    description: 'Marked area for cyclists making two-stage left turns',
    icon: '↗',
    relevantCrashModes: ['cyclist'],
    relevantSeverities: ['fatal', 'severe-injury'],
    minimumCrashThreshold: 2,
    complexity: 'quick-win',
    requires: ['signalized'],
  },
  {
    id: 'green-conflict-zone',
    category: 'cycling',
    label: 'Green conflict zone paint',
    description: 'Green pavement marking through conflict areas',
    icon: '💚',
    relevantCrashModes: ['cyclist'],
    relevantSeverities: ['fatal', 'severe-injury', 'moderate-injury'],
    minimumCrashThreshold: 1,
    complexity: 'quick-win',
  },
];

export const IMPROVEMENT_BY_ID = new Map(
  INTERSECTION_IMPROVEMENTS.map((imp) => [imp.id, imp]),
);

export const CATEGORY_LABELS: Record<string, string> = {
  'traffic-control': 'Traffic Control',
  'pedestrian': 'Pedestrian',
  'accessibility': 'Accessibility',
  'transit': 'Transit',
  'safety': 'Safety',
  'cycling': 'Cycling',
};

export const COMPLEXITY_COLORS: Record<string, string> = {
  'quick-win': '#16A34A',
  'moderate': '#CA8A04',
  'major': '#DC2626',
};

export const COMPLEXITY_LABELS: Record<string, string> = {
  'quick-win': 'Quick Win',
  'moderate': 'Moderate',
  'major': 'Major',
};
