/* eslint-disable */
/**
 * Generated by Convex — do not edit.
 * Run `npx convex dev` to regenerate.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from 'convex/server';

import type * as users from '../users.js';
import type * as hotspots from '../hotspots.js';
import type * as designs from '../designs.js';
import type * as comments from '../comments.js';
import type * as reports from '../reports.js';

declare const fullApi: ApiFromModules<{
  users: typeof users;
  hotspots: typeof hotspots;
  designs: typeof designs;
  comments: typeof comments;
  reports: typeof reports;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, 'public'>>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, 'internal'>>;
