/* eslint-disable */
/**
 * Generated by Convex — do not edit.
 * Run `npx convex dev` to regenerate.
 */

import { anyApi } from 'convex/server';

export const api = anyApi;
export const internal = anyApi;
