import type { HotspotPin, DesignPin } from '@/lib/types';

// Mock hotspots scattered across San Francisco
export const MOCK_HOTSPOTS: HotspotPin[] = [
  {
    id: 'hs-001',
    title: 'Dangerous crossing at Market & 6th',
    category: 'dangerous-intersection',
    severity: 'critical',
    status: 'open',
    lat: 37.7825,
    lng: -122.4100,
    upvotes: 142,
    commentCount: 23,
  },
  {
    id: 'hs-002',
    title: 'No bike lane on Valencia St',
    category: 'needs-bike-lane',
    severity: 'high',
    status: 'acknowledged',
    lat: 37.7597,
    lng: -122.4215,
    upvotes: 89,
    commentCount: 15,
  },
  {
    id: 'hs-003',
    title: 'Speeding on Sunset Blvd near school',
    category: 'speeding',
    severity: 'critical',
    status: 'open',
    lat: 37.7530,
    lng: -122.4940,
    upvotes: 201,
    commentCount: 47,
  },
  {
    id: 'hs-004',
    title: 'Crumbled sidewalk on Geary',
    category: 'poor-sidewalk',
    severity: 'medium',
    status: 'in-progress',
    lat: 37.7812,
    lng: -122.4456,
    upvotes: 34,
    commentCount: 8,
  },
  {
    id: 'hs-005',
    title: 'Transit gap — no bus route to Bayview',
    category: 'transit-gap',
    severity: 'high',
    status: 'open',
    lat: 37.7298,
    lng: -122.3892,
    upvotes: 115,
    commentCount: 31,
  },
  {
    id: 'hs-006',
    title: 'Missing curb ramps on Fillmore & Hayes',
    category: 'accessibility',
    severity: 'high',
    status: 'open',
    lat: 37.7755,
    lng: -122.4312,
    upvotes: 67,
    commentCount: 12,
  },
  {
    id: 'hs-007',
    title: 'Dangerous left turn at Divisadero & Fell',
    category: 'dangerous-intersection',
    severity: 'high',
    status: 'acknowledged',
    lat: 37.7730,
    lng: -122.4380,
    upvotes: 98,
    commentCount: 19,
  },
  {
    id: 'hs-008',
    title: 'Speeding corridor on 19th Ave',
    category: 'speeding',
    severity: 'critical',
    status: 'open',
    lat: 37.7468,
    lng: -122.4750,
    upvotes: 178,
    commentCount: 42,
  },
  {
    id: 'hs-009',
    title: 'Bike lane needed on Folsom St',
    category: 'needs-bike-lane',
    severity: 'medium',
    status: 'open',
    lat: 37.7887,
    lng: -122.3928,
    upvotes: 56,
    commentCount: 9,
  },
  {
    id: 'hs-010',
    title: 'Broken sidewalk near Dolores Park',
    category: 'poor-sidewalk',
    severity: 'low',
    status: 'resolved',
    lat: 37.7596,
    lng: -122.4269,
    upvotes: 28,
    commentCount: 5,
  },
  {
    id: 'hs-011',
    title: 'Inaccessible bus stop on Mission',
    category: 'accessibility',
    severity: 'high',
    status: 'in-progress',
    lat: 37.7642,
    lng: -122.4195,
    upvotes: 73,
    commentCount: 14,
  },
  {
    id: 'hs-012',
    title: 'Speeding on Portola Dr',
    category: 'speeding',
    severity: 'medium',
    status: 'open',
    lat: 37.7390,
    lng: -122.4530,
    upvotes: 41,
    commentCount: 7,
  },
  {
    id: 'hs-013',
    title: 'Dangerous merge at Octavia & Market',
    category: 'dangerous-intersection',
    severity: 'critical',
    status: 'open',
    lat: 37.7737,
    lng: -122.4240,
    upvotes: 165,
    commentCount: 36,
  },
  {
    id: 'hs-014',
    title: 'Transit service gap in Outer Richmond',
    category: 'transit-gap',
    severity: 'medium',
    status: 'open',
    lat: 37.7792,
    lng: -122.5100,
    upvotes: 53,
    commentCount: 11,
  },
  {
    id: 'hs-015',
    title: 'Need protected bike lane on Howard',
    category: 'needs-bike-lane',
    severity: 'high',
    status: 'acknowledged',
    lat: 37.7858,
    lng: -122.3985,
    upvotes: 124,
    commentCount: 28,
  },
  {
    id: 'hs-016',
    title: 'Pedestrian hazard at Columbus & Broadway',
    category: 'dangerous-intersection',
    severity: 'high',
    status: 'open',
    lat: 37.7978,
    lng: -122.4068,
    upvotes: 87,
    commentCount: 16,
  },
  {
    id: 'hs-017',
    title: 'Sidewalk flooding on Great Highway',
    category: 'other',
    severity: 'low',
    status: 'open',
    lat: 37.7635,
    lng: -122.5088,
    upvotes: 19,
    commentCount: 3,
  },
  {
    id: 'hs-018',
    title: 'No crosswalk at Cesar Chavez & Harrison',
    category: 'dangerous-intersection',
    severity: 'medium',
    status: 'open',
    lat: 37.7482,
    lng: -122.4124,
    upvotes: 45,
    commentCount: 8,
  },
];

// Mock designs scattered across San Francisco
export const MOCK_DESIGNS: DesignPin[] = [
  {
    id: 'ds-001',
    title: 'Market Street Protected Bike Corridor',
    lat: 37.7835,
    lng: -122.4090,
    upvotes: 312,
    prowagPass: true,
    templateId: 'protected-bike-01',
  },
  {
    id: 'ds-002',
    title: 'Valencia Road Diet Proposal',
    lat: 37.7580,
    lng: -122.4210,
    upvotes: 187,
    prowagPass: true,
    templateId: 'road-diet-01',
  },
  {
    id: 'ds-003',
    title: 'Embarcadero Complete Street Vision',
    lat: 37.7945,
    lng: -122.3932,
    upvotes: 256,
    prowagPass: false,
    templateId: 'complete-street-01',
  },
  {
    id: 'ds-004',
    title: 'Geary BRT Transit Priority',
    lat: 37.7815,
    lng: -122.4460,
    upvotes: 143,
    prowagPass: true,
    templateId: 'transit-priority-01',
  },
  {
    id: 'ds-005',
    title: 'Shared Space on Linden Alley',
    lat: 37.7760,
    lng: -122.4232,
    upvotes: 94,
    prowagPass: true,
    templateId: 'shared-street-01',
  },
  {
    id: 'ds-006',
    title: 'Folsom Street Redesign',
    lat: 37.7890,
    lng: -122.3945,
    upvotes: 175,
    prowagPass: false,
  },
  {
    id: 'ds-007',
    title: 'Sunset Blvd Traffic Calming',
    lat: 37.7540,
    lng: -122.4930,
    upvotes: 108,
    prowagPass: true,
  },
  {
    id: 'ds-008',
    title: 'Cesar Chavez Complete Street',
    lat: 37.7490,
    lng: -122.4130,
    upvotes: 88,
    prowagPass: true,
    templateId: 'complete-street-02',
  },
];
